# Development Stage
FROM node:22-alpine as dev

## Define working directory in container
WORKDIR /app

## Copy package.json and package-lock.json to container
COPY package.json ./
RUN npm install

## Copy all files to container
COPY . ./
CMD ["npm", "run", "dev"]

# Production Stage
FROM node:22-alpine as prod

## Define working directory in container
WORKDIR /app

## Copy package.json and package-lock.json to container
COPY package.json ./
RUN npm install

## Copy all files to container
COPY . ./
RUN npm run build

CMD ["npm", "run", "preview"]