services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
      target: dev
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://db:27017/chat-app
    depends_on:
      - db

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      target: dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5173
    depends_on:
      - backend-dev

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data: