# Development Stage
FROM node:22 -alpine as dev

## Define working directory in container
WORKDIR /app

## Copy package.json and package-lock.json to container
COPY backend/package.json ./
RUN npm install

## Copy all files to container
COPY backend/ .
CMD ["npx", "nodemon", "index.js"]

# Production Stage
FROM node:22 -alpine as prod

## Define working directory in container
WORKDIR /app

## Copy package.json and package-lock.json to container
COPY backend/package.json ./
RUN npm install

## Copy all files to container
COPY backend/ ./
CMD ["npm", "start"]